name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false
      - name: setup-ocaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0
      - name: setup-deploy
        run: |
          opam pin add . -y --no-action
          opam depext -y swhid_core
          opam install -y ./*.opam --deps-only --with-test --with-doc
          opam upgrade --fixup
          touch doc/.nojekyll
      - name: api
        run: |
          opam exec -- dune build @doc
          mv _build/default/_doc/_html/ doc/api
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/
          CLEAN: true
