version: "0.3.0+dune"
opam-version: "2.0"
synopsis: "Basic OS interaction for OCaml"
description: """\
Bos provides support for basic and robust interaction with the
operating system in OCaml. It has functions to access the process
environment, parse command line arguments, interact with the file
system and run command line programs.

Bos works equally well on POSIX and Windows operating systems.

Bos depends on [Rresult][rresult], [Astring][astring], [Fmt][fmt],
[Fpath][fpath] and [Logs][logs] and the OCaml Unix library. It is
distributed under the ISC license.

[rresult]: http://erratique.ch/software/rresult
[astring]: http://erratique.ch/software/astring
[fmt]: http://erratique.ch/software/fmt
[fpath]: http://erratique.ch/software/fpath
[logs]: http://erratique.ch/software/logs

Home page: http://erratique.ch/software/bos
Contact: Daniel Bünzli `<daniel.buenzl i@erratique.ch>`"""
maintainer: "Daniel Bünzli <daniel.buenzl i@erratique.ch>"
authors: ["Daniel Bünzli <daniel.buenzl i@erratique.ch>"]
tags: [ "os" "system" "cli" "command" "file" "path" "log" "unix" "org:erratique" ]
homepage: "https://github.com/dune-universe/bos"
bug-reports: "https://github.com/dune-universe/bos/issues"
license: "ISC"
depends: [
  "dune"
  "ocaml" {>= "4.14.0"}
  "base-unix"
  "rresult" {>= "0.7.0"}
  "astring"
  "fpath"
  "fmt" {>= "0.8.10"}
  "logs"
  "mtime" {with-test}
]
build: [[ "dune" "build" "-p" name ]]
dev-repo: "git+https://github.com/dune-universe/bos.git"