This expression evaluates to 42
This expression is printed as follows:
( 1 + 2 * 10 ) * 2
This expression is pretty-printed in 10 columns as follows:
( 1 +
  2 * 10
) *
2
This expression is pretty-printed in 20 columns as follows:
(1 + 2 * 10) * 2
This expression is pretty-printed in 40 columns as follows:
(1 + 2 * 10) * 2
This expression is pretty-printed in 80 columns as follows:
(1 + 2 * 10) * 2
