
module MenhirBasics = struct
  
  exception Error
  
  let _eRR =
    fun _s ->
      raise Error
  
  type token = 
    | TIMES
    | RPAREN
    | PLUS
    | MINUS
    | LPAREN
    | INT of 
# 1 "demos/calc/parser.mly"
       (int)
# 20 "demos/calc/parser.ml"
  
    | EOL
    | DIV
  
end

include MenhirBasics

type ('s, 'r) _menhir_state = 
  | MenhirState00 : ('s, _menhir_box_main) _menhir_state
    (** State 00.
        Stack shape : <empty>.
        Start symbol: main. *)

  | MenhirState01 : (('s, _menhir_box_main) _menhir_cell1_MINUS, _menhir_box_main) _menhir_state
    (** State 01.
        Stack shape : MINUS.
        Start symbol: main. *)

  | MenhirState02 : (('s, _menhir_box_main) _menhir_cell1_LPAREN, _menhir_box_main) _menhir_state
    (** State 02.
        Stack shape : LPAREN.
        Start symbol: main. *)

  | MenhirState05 : (('s, _menhir_box_main) _menhir_cell1_expr, _menhir_box_main) _menhir_state
    (** State 05.
        Stack shape : expr.
        Start symbol: main. *)

  | MenhirState08 : (('s, _menhir_box_main) _menhir_cell1_expr, _menhir_box_main) _menhir_state
    (** State 08.
        Stack shape : expr.
        Start symbol: main. *)

  | MenhirState10 : (('s, _menhir_box_main) _menhir_cell1_expr, _menhir_box_main) _menhir_state
    (** State 10.
        Stack shape : expr.
        Start symbol: main. *)

  | MenhirState12 : (('s, _menhir_box_main) _menhir_cell1_expr, _menhir_box_main) _menhir_state
    (** State 12.
        Stack shape : expr.
        Start symbol: main. *)


and ('s, 'r) _menhir_cell1_expr = 
  | MenhirCell1_expr of 's * ('s, 'r) _menhir_state * (int)

and ('s, 'r) _menhir_cell1_LPAREN = 
  | MenhirCell1_LPAREN of 's * ('s, 'r) _menhir_state

and ('s, 'r) _menhir_cell1_MINUS = 
  | MenhirCell1_MINUS of 's * ('s, 'r) _menhir_state

and _menhir_box_main = 
  | MenhirBox_main of (int) [@@unboxed]

let _menhir_action_1 =
  fun i ->
    (* expr -> INT *)
    (
# 21 "demos/calc/parser.mly"
    ( i )
# 84 "demos/calc/parser.ml"
     : (int))

let _menhir_action_2 =
  fun e ->
    (* expr -> LPAREN expr RPAREN *)
    (
# 23 "demos/calc/parser.mly"
    ( e )
# 93 "demos/calc/parser.ml"
     : (int))

let _menhir_action_3 =
  fun e1 e2 ->
    (* expr -> expr PLUS expr *)
    (
# 25 "demos/calc/parser.mly"
    ( e1 + e2 )
# 102 "demos/calc/parser.ml"
     : (int))

let _menhir_action_4 =
  fun e1 e2 ->
    (* expr -> expr MINUS expr *)
    (
# 27 "demos/calc/parser.mly"
    ( e1 - e2 )
# 111 "demos/calc/parser.ml"
     : (int))

let _menhir_action_5 =
  fun e1 e2 ->
    (* expr -> expr TIMES expr *)
    (
# 29 "demos/calc/parser.mly"
    ( e1 * e2 )
# 120 "demos/calc/parser.ml"
     : (int))

let _menhir_action_6 =
  fun e1 e2 ->
    (* expr -> expr DIV expr *)
    (
# 31 "demos/calc/parser.mly"
    ( e1 / e2 )
# 129 "demos/calc/parser.ml"
     : (int))

let _menhir_action_7 =
  fun e ->
    (* expr -> MINUS expr *)
    (
# 33 "demos/calc/parser.mly"
    ( - e )
# 138 "demos/calc/parser.ml"
     : (int))

let _menhir_action_8 =
  fun e ->
    (* main -> expr EOL *)
    (
# 17 "demos/calc/parser.mly"
    ( e )
# 147 "demos/calc/parser.ml"
     : (int))

let _menhir_print_token : token -> string =
  fun _tok ->
    match _tok with
    | TIMES ->
        "TIMES"
    | RPAREN ->
        "RPAREN"
    | PLUS ->
        "PLUS"
    | MINUS ->
        "MINUS"
    | LPAREN ->
        "LPAREN"
    | INT _ ->
        "INT"
    | EOL ->
        "EOL"
    | DIV ->
        "DIV"

let _menhir_fail : unit -> 'a =
  fun () ->
    Printf.eprintf "Internal failure -- please contact the parser generator's developers.\n%!";
    assert false

include struct
  
  [@@@ocaml.warning "-4-37"]
  
  let rec _menhir_run_01 : type  ttv_stack. ttv_stack -> _ -> _ -> (ttv_stack, _menhir_box_main) _menhir_state -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer _menhir_s ->
      (* State 1: *)
      let _menhir_stack = MenhirCell1_MINUS (_menhir_stack, _menhir_s) in
      let _tok = _menhir_lexer _menhir_lexbuf in
      match (_tok : MenhirBasics.token) with
      | MINUS ->
          (* Shifting (MINUS) to state 1 *)
          _menhir_run_01 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState01
      | LPAREN ->
          (* Shifting (LPAREN) to state 2 *)
          _menhir_run_02 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState01
      | INT _v ->
          (* Shifting (INT) to state 3 *)
          (* State 3: *)
          let _tok = _menhir_lexer _menhir_lexbuf in
          (* Reducing production expr -> INT *)
          let i = _v in
          let _v = _menhir_action_1 i in
          _menhir_run_14 _menhir_stack _menhir_lexbuf _menhir_lexer _v _tok
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
  and _menhir_run_02 : type  ttv_stack. ttv_stack -> _ -> _ -> (ttv_stack, _menhir_box_main) _menhir_state -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer _menhir_s ->
      (* State 2: *)
      let _menhir_stack = MenhirCell1_LPAREN (_menhir_stack, _menhir_s) in
      let _tok = _menhir_lexer _menhir_lexbuf in
      match (_tok : MenhirBasics.token) with
      | MINUS ->
          (* Shifting (MINUS) to state 1 *)
          _menhir_run_01 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState02
      | LPAREN ->
          (* Shifting (LPAREN) to state 2 *)
          _menhir_run_02 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState02
      | INT _v ->
          (* Shifting (INT) to state 3 *)
          (* State 3: *)
          let _tok = _menhir_lexer _menhir_lexbuf in
          (* Reducing production expr -> INT *)
          let i = _v in
          let _v = _menhir_action_1 i in
          _menhir_run_04 _menhir_stack _menhir_lexbuf _menhir_lexer _v MenhirState02 _tok
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
  and _menhir_run_04 : type  ttv_stack. ((ttv_stack, _menhir_box_main) _menhir_cell1_LPAREN as 'stack) -> _ -> _ -> _ -> ('stack, _menhir_box_main) _menhir_state -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok ->
      (* State 4: *)
      match (_tok : MenhirBasics.token) with
      | TIMES ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (TIMES) to state 5 *)
          _menhir_run_05 _menhir_stack _menhir_lexbuf _menhir_lexer
      | RPAREN ->
          (* Shifting (RPAREN) to state 7 *)
          (* State 7: *)
          let _tok = _menhir_lexer _menhir_lexbuf in
          let MenhirCell1_LPAREN (_menhir_stack, _menhir_s) = _menhir_stack in
          (* Reducing production expr -> LPAREN expr RPAREN *)
          let e = _v in
          let _v = _menhir_action_2 e in
          _menhir_goto_expr _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok
      | PLUS ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (PLUS) to state 8 *)
          _menhir_run_08 _menhir_stack _menhir_lexbuf _menhir_lexer
      | MINUS ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (MINUS) to state 12 *)
          _menhir_run_12 _menhir_stack _menhir_lexbuf _menhir_lexer
      | DIV ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (DIV) to state 10 *)
          _menhir_run_10 _menhir_stack _menhir_lexbuf _menhir_lexer
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
  and _menhir_run_05 : type  ttv_stack. (ttv_stack, _menhir_box_main) _menhir_cell1_expr -> _ -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer ->
      (* State 5: *)
      let _tok = _menhir_lexer _menhir_lexbuf in
      match (_tok : MenhirBasics.token) with
      | MINUS ->
          (* Shifting (MINUS) to state 1 *)
          _menhir_run_01 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState05
      | LPAREN ->
          (* Shifting (LPAREN) to state 2 *)
          _menhir_run_02 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState05
      | INT _v ->
          (* Shifting (INT) to state 3 *)
          (* State 3: *)
          let _tok = _menhir_lexer _menhir_lexbuf in
          (* Reducing production expr -> INT *)
          let i = _v in
          let _v = _menhir_action_1 i in
          _menhir_run_06 _menhir_stack _menhir_lexbuf _menhir_lexer _v _tok
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
  and _menhir_run_06 : type  ttv_stack. (ttv_stack, _menhir_box_main) _menhir_cell1_expr -> _ -> _ -> _ -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer _v _tok ->
      (* State 6: *)
      let MenhirCell1_expr (_menhir_stack, _menhir_s, e1) = _menhir_stack in
      (* Reducing production expr -> expr TIMES expr *)
      let e2 = _v in
      let _v = _menhir_action_5 e1 e2 in
      _menhir_goto_expr _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok
  
  and _menhir_goto_expr : type  ttv_stack. ttv_stack -> _ -> _ -> _ -> (ttv_stack, _menhir_box_main) _menhir_state -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok ->
      match _menhir_s with
      | MenhirState02 ->
          _menhir_run_04 _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok
      | MenhirState05 ->
          _menhir_run_06 _menhir_stack _menhir_lexbuf _menhir_lexer _v _tok
      | MenhirState08 ->
          _menhir_run_09 _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok
      | MenhirState10 ->
          _menhir_run_11 _menhir_stack _menhir_lexbuf _menhir_lexer _v _tok
      | MenhirState12 ->
          _menhir_run_13 _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok
      | MenhirState01 ->
          _menhir_run_14 _menhir_stack _menhir_lexbuf _menhir_lexer _v _tok
      | MenhirState00 ->
          _menhir_run_16 _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok
  
  and _menhir_run_09 : type  ttv_stack. ((ttv_stack, _menhir_box_main) _menhir_cell1_expr as 'stack) -> _ -> _ -> _ -> ('stack, _menhir_box_main) _menhir_state -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok ->
      (* State 9: *)
      match (_tok : MenhirBasics.token) with
      | TIMES ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (TIMES) to state 5 *)
          _menhir_run_05 _menhir_stack _menhir_lexbuf _menhir_lexer
      | DIV ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (DIV) to state 10 *)
          _menhir_run_10 _menhir_stack _menhir_lexbuf _menhir_lexer
      | EOL | MINUS | PLUS | RPAREN ->
          let MenhirCell1_expr (_menhir_stack, _menhir_s, e1) = _menhir_stack in
          (* Reducing production expr -> expr PLUS expr *)
          let e2 = _v in
          let _v = _menhir_action_3 e1 e2 in
          _menhir_goto_expr _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
  and _menhir_run_10 : type  ttv_stack. (ttv_stack, _menhir_box_main) _menhir_cell1_expr -> _ -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer ->
      (* State 10: *)
      let _tok = _menhir_lexer _menhir_lexbuf in
      match (_tok : MenhirBasics.token) with
      | MINUS ->
          (* Shifting (MINUS) to state 1 *)
          _menhir_run_01 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState10
      | LPAREN ->
          (* Shifting (LPAREN) to state 2 *)
          _menhir_run_02 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState10
      | INT _v ->
          (* Shifting (INT) to state 3 *)
          (* State 3: *)
          let _tok = _menhir_lexer _menhir_lexbuf in
          (* Reducing production expr -> INT *)
          let i = _v in
          let _v = _menhir_action_1 i in
          _menhir_run_11 _menhir_stack _menhir_lexbuf _menhir_lexer _v _tok
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
  and _menhir_run_11 : type  ttv_stack. (ttv_stack, _menhir_box_main) _menhir_cell1_expr -> _ -> _ -> _ -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer _v _tok ->
      (* State 11: *)
      let MenhirCell1_expr (_menhir_stack, _menhir_s, e1) = _menhir_stack in
      (* Reducing production expr -> expr DIV expr *)
      let e2 = _v in
      let _v = _menhir_action_6 e1 e2 in
      _menhir_goto_expr _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok
  
  and _menhir_run_13 : type  ttv_stack. ((ttv_stack, _menhir_box_main) _menhir_cell1_expr as 'stack) -> _ -> _ -> _ -> ('stack, _menhir_box_main) _menhir_state -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok ->
      (* State 13: *)
      match (_tok : MenhirBasics.token) with
      | TIMES ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (TIMES) to state 5 *)
          _menhir_run_05 _menhir_stack _menhir_lexbuf _menhir_lexer
      | DIV ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (DIV) to state 10 *)
          _menhir_run_10 _menhir_stack _menhir_lexbuf _menhir_lexer
      | EOL | MINUS | PLUS | RPAREN ->
          let MenhirCell1_expr (_menhir_stack, _menhir_s, e1) = _menhir_stack in
          (* Reducing production expr -> expr MINUS expr *)
          let e2 = _v in
          let _v = _menhir_action_4 e1 e2 in
          _menhir_goto_expr _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
  and _menhir_run_14 : type  ttv_stack. (ttv_stack, _menhir_box_main) _menhir_cell1_MINUS -> _ -> _ -> _ -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer _v _tok ->
      (* State 14: *)
      let MenhirCell1_MINUS (_menhir_stack, _menhir_s) = _menhir_stack in
      (* Reducing production expr -> MINUS expr *)
      let e = _v in
      let _v = _menhir_action_7 e in
      _menhir_goto_expr _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok
  
  and _menhir_run_16 : type  ttv_stack. ttv_stack -> _ -> _ -> _ -> (ttv_stack, _menhir_box_main) _menhir_state -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer _v _menhir_s _tok ->
      (* State 16: *)
      match (_tok : MenhirBasics.token) with
      | TIMES ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (TIMES) to state 5 *)
          _menhir_run_05 _menhir_stack _menhir_lexbuf _menhir_lexer
      | PLUS ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (PLUS) to state 8 *)
          _menhir_run_08 _menhir_stack _menhir_lexbuf _menhir_lexer
      | MINUS ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (MINUS) to state 12 *)
          _menhir_run_12 _menhir_stack _menhir_lexbuf _menhir_lexer
      | EOL ->
          (* Shifting (EOL) to state 17 *)
          (* State 17: *)
          (* Reducing production main -> expr EOL *)
          let e = _v in
          let _v = _menhir_action_8 e in
          (* State 15: *)
          (* Accepting *)
          MenhirBox_main _v
      | DIV ->
          let _menhir_stack = MenhirCell1_expr (_menhir_stack, _menhir_s, _v) in
          (* Shifting (DIV) to state 10 *)
          _menhir_run_10 _menhir_stack _menhir_lexbuf _menhir_lexer
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
  and _menhir_run_08 : type  ttv_stack. (ttv_stack, _menhir_box_main) _menhir_cell1_expr -> _ -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer ->
      (* State 8: *)
      let _tok = _menhir_lexer _menhir_lexbuf in
      match (_tok : MenhirBasics.token) with
      | MINUS ->
          (* Shifting (MINUS) to state 1 *)
          _menhir_run_01 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState08
      | LPAREN ->
          (* Shifting (LPAREN) to state 2 *)
          _menhir_run_02 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState08
      | INT _v ->
          (* Shifting (INT) to state 3 *)
          (* State 3: *)
          let _tok = _menhir_lexer _menhir_lexbuf in
          (* Reducing production expr -> INT *)
          let i = _v in
          let _v = _menhir_action_1 i in
          _menhir_run_09 _menhir_stack _menhir_lexbuf _menhir_lexer _v MenhirState08 _tok
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
  and _menhir_run_12 : type  ttv_stack. (ttv_stack, _menhir_box_main) _menhir_cell1_expr -> _ -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer ->
      (* State 12: *)
      let _tok = _menhir_lexer _menhir_lexbuf in
      match (_tok : MenhirBasics.token) with
      | MINUS ->
          (* Shifting (MINUS) to state 1 *)
          _menhir_run_01 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState12
      | LPAREN ->
          (* Shifting (LPAREN) to state 2 *)
          _menhir_run_02 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState12
      | INT _v ->
          (* Shifting (INT) to state 3 *)
          (* State 3: *)
          let _tok = _menhir_lexer _menhir_lexbuf in
          (* Reducing production expr -> INT *)
          let i = _v in
          let _v = _menhir_action_1 i in
          _menhir_run_13 _menhir_stack _menhir_lexbuf _menhir_lexer _v MenhirState12 _tok
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
  let _menhir_run_00 : type  ttv_stack. ttv_stack -> _ -> _ -> _menhir_box_main =
    fun _menhir_stack _menhir_lexbuf _menhir_lexer ->
      (* State 0: *)
      let _tok = _menhir_lexer _menhir_lexbuf in
      match (_tok : MenhirBasics.token) with
      | MINUS ->
          (* Shifting (MINUS) to state 1 *)
          _menhir_run_01 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState00
      | LPAREN ->
          (* Shifting (LPAREN) to state 2 *)
          _menhir_run_02 _menhir_stack _menhir_lexbuf _menhir_lexer MenhirState00
      | INT _v ->
          (* Shifting (INT) to state 3 *)
          (* State 3: *)
          let _tok = _menhir_lexer _menhir_lexbuf in
          (* Reducing production expr -> INT *)
          let i = _v in
          let _v = _menhir_action_1 i in
          _menhir_run_16 _menhir_stack _menhir_lexbuf _menhir_lexer _v MenhirState00 _tok
      | _ ->
          (* Initiating error handling *)
          _eRR ()
  
end

let main =
  fun _menhir_lexer _menhir_lexbuf ->
    let _menhir_stack = () in
    let MenhirBox_main v = _menhir_run_00 _menhir_stack _menhir_lexbuf _menhir_lexer in
    v
